import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://thevapesinmumbai.com";
  const now = new Date();

  return [
    { url: base, lastModified: now, changeFrequency: "daily", priority: 1.0 },
    { url: `${base}/products/disposables`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/products/pod-systems`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/products/eliquids`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/products/nicotine-pouches`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/products/tobacco`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/blog/best-vape-shops-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/vape-delivery-mumbai-guide`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/where-to-buy-vapes-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/elfbar-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/caliburn-pod-system-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/zyn-nicotine-pouches-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/trusted-vape-delivery-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/nicotine-content-guide-mumbai`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/locations/andheri-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/andheri-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/bandra-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/bandra-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/belapur`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/bkc`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/borivali-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/borivali-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/chembur`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/colaba`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/dadar-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/dadar-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/dahisar`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/ghatkopar-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/ghatkopar-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/goregaon-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/goregaon-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/grant-road`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/jogeshwari-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/jogeshwari-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/juhu`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/kandivali-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/kandivali-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/khar-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/kharghar`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/kurla`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/lower-parel`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/malabar-hill`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/malad-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/malad-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/marine-lines`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/matunga`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/mulund-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/mulund-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/nerul`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/parel`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/powai`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/santacruz-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/santacruz-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/sion`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/tardeo`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/thane-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/thane-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/vashi`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/versova`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/vikhroli`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/vile-parle-east`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/vile-parle-west`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/locations/worli`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];
}
